#Going to be doing Maky things
test:   GarageDoorOpener.cpp
	g++ -o garageSim GarageDoorOpener.cpp IRBeam.cpp GarageDoorRemote.cpp Motor.cpp

butt_test:   GarageDoorOpener.cpp
	g++ -D QUICK_BUTT_TEST -o garageSim GarageDoorOpener.cpp IRBeam.cpp GarageDoorRemote.cpp Motor.cpp
